### ISSUE TITLE
Error: Type 'FontFeature' not found

### ISSUE THREAD

**Issue by jabele** [material-foundation/flutter-packages#567]
### Package

google_fonts

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

### What happened?

Getting a Major Bug in 6.2.0:
Error (Xcode): ../../.pub-cache/hosted/pub.dev/google_fonts-6.2.0/lib/src/google_fonts_base.dart:69:8: Error: Type 'FontFeature' not found

**Comment by Mamun-Lab** [comment]
I am facing the same issue . No solution yet.

**Comment by breathingcyborg** [comment]
Its probably because of this commit. https://github.com/material-foundation/flutter-packages/commit/e32cc8e6546b5cf12cc2e6a456f0428f68f59d8a

FontFeature is defined in dart:ui. And this commit removed it.
For now downgrading to google_fonts version 6.1.0 would work.

**Comment by RaminBgrn** [comment]
I solved the problem temporarily with version 5.1.0

**Comment by michaelnabil230** [comment]
I am facing the same issue. No solution yet.

**Comment by guidezpl** [comment]
Sorry about the inconvenience, I believe this is caused by using an older flutter version, because the following checks pass

- [stable](https://github.com/material-foundation/flutter-packages/actions/runs/8116758673/job/22187475530)
- [beta](https://github.com/material-foundation/flutter-packages/actions/runs/8116758673/job/22187475772)

You can upgrade flutter with `flutter upgrade`. I've published a patch `6.2.1` that restricts this package to the current flutter stable and newer versions.
